name: techbox
description: "E-Commerce App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  another_flutter_splash_screen: ^1.2.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  smooth_page_indicator: ^1.2.1
  google_nav_bar: ^5.0.7
  equatable: ^2.0.7
  flutter_riverpod: ^2.6.1
  http: ^1.4.0
  dartz: ^0.10.1
  toastification: ^3.0.3
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.2.0
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.20.2
  pinput: ^5.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/image/
    - .env

fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter_18pt-Regular.ttf
      - asset: assets/fonts/Inter_18pt-Medium.ttf
        weight: 500
      - asset: assets/fonts/Inter_18pt-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Inter_18pt-Bold.ttf
        weight: 700
      - asset: assets/fonts/Inter_18pt-Italic.ttf
        style: italic
